services:
  - type: web
    name: tlabs-learning-hub
    env: node
    plan: free
    buildCommand: npm install && npm run db:migrate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        value: /data/data.db
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
